(require :settings)
(require :mapping)
(require :neovide)

; Plugins
(require :plugins.theme)
(require :plugins.telescope)
(require :plugins.treesitter)
(require :plugins.which_key)
(require :plugins.comment)
(require :plugins.completions)
(require :plugins.lsp_config)
(require :plugins.toggleterm)
(require :plugins.lualine)
(require :plugins.alpha)
(require :plugins.noice)
(require :plugins.nvim_tree)
(require :plugins.leap)
(require :plugins.eyeliner)

