(set vim.opt.nu true)
(set vim.opt.relativenumber true)
(set vim.opt.tabstop 2)
(set vim.opt.softtabstop 2)
(set vim.opt.shiftwidth 2)
(set vim.opt.expandtab true)
(set vim.opt.scrolloff 8)
(set vim.o.clipboard :unnamedplus)
(set vim.o.undofile true)
(set vim.o.ignorecase true)
(set vim.o.smartcase true)
(set vim.o.termguicolors true)
(set vim.o.mouse :a)

